In [2]:
import pandas as pd

In [11]:
df = pd.read_csv("nba/Advanced.csv")

In [12]:
df.to_csv("advanced_clean.csv", index=False)

In [13]:
df

,seas_id,season,player_id,player,birth_year,pos,age,experience,lg,tm,...,tov_percent,usg_percent,ows,dws,ws,ws_48,obpm,dbpm,bpm,vorp
0,31871,2025,5025,A.J. Green,NaN,SG,25.0,3,NBA,MIL,...,8.1,13.6,0.7,0.2,0.9,0.119,0.2,-0.5,-0.4,0.2
1,31872,2025,5210,AJ Johnson,NaN,SG,20.0,1,NBA,MIL,...,25.0,22.0,0.0,0.0,0.0,-0.237,-10.1,-4.8,-14.9,0.0
2,31873,2025,4219,Aaron Gordon,NaN,PF,29.0,11,NBA,DEN,...,10.0,18.1,0.7,0.1,0.8,0.185,4.4,-0.6,3.8,0.3
3,31874,2025,4582,Aaron Holiday,NaN,PG,28.0,7,NBA,HOU,...,8.1,15.8,0.2,0.1,0.4,0.183,1.4,0.6,2.0,0.1
4,31875,2025,4805,Aaron Nesmith,NaN,SF,25.0,5,NBA,IND,...,10.7,14.9,0.2,0.1,0.3,0.100,-2.1,-0.5,-2.5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32353,200,1947,157,Walt Miller,NaN,F,31.0,1,BAA,PIT,...,NaN,NaN,0.3,-0.1,0.3,NaN,NaN,NaN,NaN,NaN
32354,201,1947,158,Warren Fenley,NaN,F,24.0,1,BAA,BOS,...,NaN,NaN,-0.4,0.3,-0.1,NaN,NaN,NaN,NaN,NaN
32355,202,1947,159,Wilbert Kautz,NaN,G-F,31.0,1,BAA,CHS,...,NaN,NaN,-0.7,1.5,0.8,NaN,NaN,NaN,NaN,NaN
32356,203,1947,160,Woody Grimshaw,NaN,G,27.0,1,BAA,PRO,...,NaN,NaN,0.6,0.0,0.6,NaN,NaN,NaN,NaN,NaN
32357,204,1947,161,Wyndol Gray,NaN,G-F,24.0,1,BAA,BOS,...,NaN,NaN,1.6,0.7,2.2,NaN,NaN,NaN,NaN,NaN

# Populate the Database

In [18]:
from sqlalchemy import create_engine

# Database connection details
MYSQL_USER = "admin"
MYSQL_PASSWORD = "31cuCUMbers"
MYSQL_HOST = "134.122.79.205"
MYSQL_PORT = 3306
MYSQL_DATABASE = "cucumdb"

# Create SQLAlchemy engine
engine = create_engine(
    f"mysql+pymysql://{MYSQL_USER}:{MYSQL_PASSWORD}@{MYSQL_HOST}:{MYSQL_PORT}/{MYSQL_DATABASE}"
)

In [27]:
import os

nba_folder = "nba"
nba_files = [f for f in os.listdir(nba_folder) if f.endswith('.csv')]
nba_file_paths = [os.path.abspath(os.path.join(nba_folder, f)) for f in nba_files]
nba_file_paths

['/Users/mertbozkurtlar/Documents/GitHub/cucumbers/raw_data/nba/Team Stats Per 100 Poss.csv',
 '/Users/mertbozkurtlar/Documents/GitHub/cucumbers/raw_data/nba/Team Totals.csv',
 '/Users/mertbozkurtlar/Documents/GitHub/cucumbers/raw_data/nba/Player Per Game.csv',
 '/Users/mertbozkurtlar/Documents/GitHub/cucumbers/raw_data/nba/Advanced.csv',
 '/Users/mertbozkurtlar/Documents/GitHub/cucumbers/raw_data/nba/End of Season Teams.csv',
 '/Users/mertbozkurtlar/Documents/GitHub/cucumbers/raw_data/nba/Opponent Stats Per 100 Poss.csv',
 '/Users/mertbozkurtlar/Documents/GitHub/cucumbers/raw_data/nba/Player Career Info.csv',
 '/Users/mertbozkurtlar/Documents/GitHub/cucumbers/raw_data/nba/End of Season Teams Voting.csv',
 '/Users/mertbozkurtlar/Documents/GitHub/cucumbers/raw_data/nba/Player Totals.csv',
 '/Users/mertbozkurtlar/Documents/GitHub/cucumbers/raw_data/nba/Player Play By Play.csv',
 '/Users/mertbozkurtlar/Documents/GitHub/cucumbers/raw_data/nba/Player Season Info.csv',
 '/Users/mertbozkurtlar/Documents/GitHub/cucumbers/raw_data/nba/All-Star Selections.csv',
 '/Users/mertbozkurtlar/Documents/GitHub/cucumbers/raw_data/nba/Team Abbrev.csv',
 '/Users/mertbozkurtlar/Documents/GitHub/cucumbers/raw_data/nba/Per 36 Minutes.csv',
 '/Users/mertbozkurtlar/Documents/GitHub/cucumbers/raw_data/nba/Opponent Stats Per Game.csv',
 '/Users/mertbozkurtlar/Documents/GitHub/cucumbers/raw_data/nba/Team Summaries.csv',
 '/Users/mertbozkurtlar/Documents/GitHub/cucumbers/raw_data/nba/Player Shooting.csv',
 '/Users/mertbozkurtlar/Documents/GitHub/cucumbers/raw_data/nba/Team Stats Per Game.csv',
 '/Users/mertbozkurtlar/Documents/GitHub/cucumbers/raw_data/nba/Per 100 Poss.csv',
 '/Users/mertbozkurtlar/Documents/GitHub/cucumbers/raw_data/nba/Opponent Totals.csv',
 '/Users/mertbozkurtlar/Documents/GitHub/cucumbers/raw_data/nba/Player Award Shares.csv']

In [29]:
for path in nba_file_paths:
    table_name = os.path.splitext(os.path.basename(path))[0]
    print("Uploading", table_name)
    table_name = table_name.replace(" ", "_")
    df = pd.read_csv(path)
    df.to_sql(
        table_name,
        engine,
        if_exists='replace',
        index=False
    )
    print("Uploaded", table_name)

Uploading Team Stats Per 100 Poss
Uploaded Team_Stats_Per_100_Poss
Uploading Team Totals
Uploaded Team_Totals
Uploading Player Per Game
Uploaded Player_Per_Game
Uploading Advanced
Uploaded Advanced
Uploading End of Season Teams
Uploaded End_of_Season_Teams
Uploading Opponent Stats Per 100 Poss
Uploaded Opponent_Stats_Per_100_Poss
Uploading Player Career Info
Uploaded Player_Career_Info
Uploading End of Season Teams Voting
Uploaded End_of_Season_Teams_Voting
Uploading Player Totals
Uploaded Player_Totals
Uploading Player Play By Play
Uploaded Player_Play_By_Play
Uploading Player Season Info
Uploaded Player_Season_Info
Uploading All-Star Selections
Uploaded All-Star_Selections
Uploading Team Abbrev
Uploaded Team_Abbrev
Uploading Per 36 Minutes
Uploaded Per_36_Minutes
Uploading Opponent Stats Per Game
Uploaded Opponent_Stats_Per_Game
Uploading Team Summaries
Uploaded Team_Summaries
Uploading Player Shooting
Uploaded Player_Shooting
Uploading Team Stats Per Game
Uploaded Team_Stats_Per_Game
Uploading Per 100 Poss
Uploaded Per_100_Poss
Uploading Opponent Totals
Uploaded Opponent_Totals
Uploading Player Award Shares
Uploaded Player_Award_Shares