In [1]:
import pandas as pd

In [11]:
df = pd.read_csv("nba/Advanced.csv")

In [12]:
df.to_csv("advanced_clean.csv", index=False)

In [13]:
df

,seas_id,season,player_id,player,birth_year,pos,age,experience,lg,tm,...,tov_percent,usg_percent,ows,dws,ws,ws_48,obpm,dbpm,bpm,vorp
0,31871,2025,5025,A.J. Green,NaN,SG,25.0,3,NBA,MIL,...,8.1,13.6,0.7,0.2,0.9,0.119,0.2,-0.5,-0.4,0.2
1,31872,2025,5210,AJ Johnson,NaN,SG,20.0,1,NBA,MIL,...,25.0,22.0,0.0,0.0,0.0,-0.237,-10.1,-4.8,-14.9,0.0
2,31873,2025,4219,Aaron Gordon,NaN,PF,29.0,11,NBA,DEN,...,10.0,18.1,0.7,0.1,0.8,0.185,4.4,-0.6,3.8,0.3
3,31874,2025,4582,Aaron Holiday,NaN,PG,28.0,7,NBA,HOU,...,8.1,15.8,0.2,0.1,0.4,0.183,1.4,0.6,2.0,0.1
4,31875,2025,4805,Aaron Nesmith,NaN,SF,25.0,5,NBA,IND,...,10.7,14.9,0.2,0.1,0.3,0.100,-2.1,-0.5,-2.5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32353,200,1947,157,Walt Miller,NaN,F,31.0,1,BAA,PIT,...,NaN,NaN,0.3,-0.1,0.3,NaN,NaN,NaN,NaN,NaN
32354,201,1947,158,Warren Fenley,NaN,F,24.0,1,BAA,BOS,...,NaN,NaN,-0.4,0.3,-0.1,NaN,NaN,NaN,NaN,NaN
32355,202,1947,159,Wilbert Kautz,NaN,G-F,31.0,1,BAA,CHS,...,NaN,NaN,-0.7,1.5,0.8,NaN,NaN,NaN,NaN,NaN
32356,203,1947,160,Woody Grimshaw,NaN,G,27.0,1,BAA,PRO,...,NaN,NaN,0.6,0.0,0.6,NaN,NaN,NaN,NaN,NaN
32357,204,1947,161,Wyndol Gray,NaN,G-F,24.0,1,BAA,BOS,...,NaN,NaN,1.6,0.7,2.2,NaN,NaN,NaN,NaN,NaN

# Populate the Database

In [2]:
from sqlalchemy import create_engine

# Database connection details
MYSQL_USER = "admin"
MYSQL_PASSWORD = "31cuCUMbers"
MYSQL_HOST = "134.122.79.205"
MYSQL_PORT = 3306
MYSQL_DATABASE = "cucumdb"

# Create SQLAlchemy engine
engine = create_engine(
    f"mysql+pymysql://{MYSQL_USER}:{MYSQL_PASSWORD}@{MYSQL_HOST}:{MYSQL_PORT}/{MYSQL_DATABASE}"
)

In [4]:
import os

nba_folder = "/Users/mertbozkurtlar/Documents/GitHub/cucumbers/raw_data/nba"
nba_files = [f for f in os.listdir(nba_folder) if f.endswith('.csv')]
nba_file_paths = [os.path.abspath(os.path.join(nba_folder, f)) for f in nba_files]
nba_file_paths

['/Users/mertbozkurtlar/Documents/GitHub/cucumbers/raw_data/nba/Team Stats Per 100 Poss.csv',
 '/Users/mertbozkurtlar/Documents/GitHub/cucumbers/raw_data/nba/Team Totals.csv',
 '/Users/mertbozkurtlar/Documents/GitHub/cucumbers/raw_data/nba/Player Per Game.csv',
 '/Users/mertbozkurtlar/Documents/GitHub/cucumbers/raw_data/nba/Advanced.csv',
 '/Users/mertbozkurtlar/Documents/GitHub/cucumbers/raw_data/nba/NBA Finals and MVP.csv',
 '/Users/mertbozkurtlar/Documents/GitHub/cucumbers/raw_data/nba/End of Season Teams.csv',
 '/Users/mertbozkurtlar/Documents/GitHub/cucumbers/raw_data/nba/Opponent Stats Per 100 Poss.csv',
 '/Users/mertbozkurtlar/Documents/GitHub/cucumbers/raw_data/nba/Player Career Info.csv',
 '/Users/mertbozkurtlar/Documents/GitHub/cucumbers/raw_data/nba/End of Season Teams Voting.csv',
 '/Users/mertbozkurtlar/Documents/GitHub/cucumbers/raw_data/nba/Player Totals.csv',
 '/Users/mertbozkurtlar/Documents/GitHub/cucumbers/raw_data/nba/Player Play By Play.csv',
 '/Users/mertbozkurtlar/Documents/GitHub/cucumbers/raw_data/nba/Player_Award_Shares.csv',
 '/Users/mertbozkurtlar/Documents/GitHub/cucumbers/raw_data/nba/Player Season Info.csv',
 '/Users/mertbozkurtlar/Documents/GitHub/cucumbers/raw_data/nba/All-Star Selections.csv',
 '/Users/mertbozkurtlar/Documents/GitHub/cucumbers/raw_data/nba/Team Abbrev.csv',
 '/Users/mertbozkurtlar/Documents/GitHub/cucumbers/raw_data/nba/Per 36 Minutes.csv',
 '/Users/mertbozkurtlar/Documents/GitHub/cucumbers/raw_data/nba/Opponent Stats Per Game.csv',
 '/Users/mertbozkurtlar/Documents/GitHub/cucumbers/raw_data/nba/Team Summaries.csv',
 '/Users/mertbozkurtlar/Documents/GitHub/cucumbers/raw_data/nba/Player Shooting.csv',
 '/Users/mertbozkurtlar/Documents/GitHub/cucumbers/raw_data/nba/Team Stats Per Game.csv',
 '/Users/mertbozkurtlar/Documents/GitHub/cucumbers/raw_data/nba/Per 100 Poss.csv',
 '/Users/mertbozkurtlar/Documents/GitHub/cucumbers/raw_data/nba/Opponent Totals.csv']

In [5]:
for path in nba_file_paths:
    table_name = os.path.splitext(os.path.basename(path))[0]
    print("Uploading", table_name)
    table_name = table_name.replace(" ", "_")
    df = pd.read_csv(path)
    df.to_sql(
        table_name,
        engine,
        if_exists='replace',
        index=False
    )
    print("Uploaded", table_name)

Uploading Team Stats Per 100 Poss
Uploaded Team_Stats_Per_100_Poss
Uploading Team Totals
Uploaded Team_Totals
Uploading Player Per Game
Uploaded Player_Per_Game
Uploading Advanced
Uploaded Advanced
Uploading NBA Finals and MVP
Uploaded NBA_Finals_and_MVP
Uploading End of Season Teams
Uploaded End_of_Season_Teams
Uploading Opponent Stats Per 100 Poss
Uploaded Opponent_Stats_Per_100_Poss
Uploading Player Career Info
Uploaded Player_Career_Info
Uploading End of Season Teams Voting
Uploaded End_of_Season_Teams_Voting
Uploading Player Totals
Uploaded Player_Totals
Uploading Player Play By Play
Uploaded Player_Play_By_Play
Uploading Player_Award_Shares
Uploaded Player_Award_Shares
Uploading Player Season Info
Uploaded Player_Season_Info
Uploading All-Star Selections
Uploaded All-Star_Selections
Uploading Team Abbrev
Uploaded Team_Abbrev
Uploading Per 36 Minutes
Uploaded Per_36_Minutes
Uploading Opponent Stats Per Game
Uploaded Opponent_Stats_Per_Game
Uploading Team Summaries
Uploaded Team_Summaries
Uploading Player Shooting
Uploaded Player_Shooting
Uploading Team Stats Per Game
Uploaded Team_Stats_Per_Game
Uploading Per 100 Poss
Uploaded Per_100_Poss
Uploading Opponent Totals
Uploaded Opponent_Totals

In [6]:
from sqlalchemy import text

with engine.connect() as connection:
    # 1. Get all tables from the current database
    tables_result = connection.execute(text("SHOW TABLES"))
    tables = [row[0] for row in tables_result.fetchall()]

    # 2. For each table, retrieve the CREATE TABLE statement and print it
    for table_name in tables:
        create_stmt_result = connection.execute(
            text(f"SHOW CREATE TABLE `{table_name}`")
        ).fetchone()
        
        # The second element in the returned tuple is the CREATE statement
        print(f"--- Schema for table: {table_name} ---")
        print(create_stmt_result[1])
        print()

--- Schema for table: Advanced ---
CREATE TABLE `Advanced` (
  `seas_id` bigint DEFAULT NULL,
  `season` bigint DEFAULT NULL,
  `player_id` bigint DEFAULT NULL,
  `player` text,
  `birth_year` double DEFAULT NULL,
  `pos` text,
  `age` double DEFAULT NULL,
  `experience` bigint DEFAULT NULL,
  `lg` text,
  `tm` text,
  `g` bigint DEFAULT NULL,
  `mp` double DEFAULT NULL,
  `per` double DEFAULT NULL,
  `ts_percent` double DEFAULT NULL,
  `x3p_ar` double DEFAULT NULL,
  `f_tr` double DEFAULT NULL,
  `orb_percent` double DEFAULT NULL,
  `drb_percent` double DEFAULT NULL,
  `trb_percent` double DEFAULT NULL,
  `ast_percent` double DEFAULT NULL,
  `stl_percent` double DEFAULT NULL,
  `blk_percent` double DEFAULT NULL,
  `tov_percent` double DEFAULT NULL,
  `usg_percent` double DEFAULT NULL,
  `ows` double DEFAULT NULL,
  `dws` double DEFAULT NULL,
  `ws` double DEFAULT NULL,
  `ws_48` double DEFAULT NULL,
  `obpm` double DEFAULT NULL,
  `dbpm` double DEFAULT NULL,
  `bpm` double DEFAULT NULL,
  `vorp` double DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

--- Schema for table: All-Star_Selections ---
CREATE TABLE `All-Star_Selections` (
  `player` text,
  `team` text,
  `lg` text,
  `season` bigint DEFAULT NULL,
  `replaced` tinyint(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

--- Schema for table: End_of_Season_Teams ---
CREATE TABLE `End_of_Season_Teams` (
  `season` bigint DEFAULT NULL,
  `lg` text,
  `type` text,
  `number_tm` text,
  `player` text,
  `position` text,
  `seas_id` bigint DEFAULT NULL,
  `player_id` bigint DEFAULT NULL,
  `birth_year` double DEFAULT NULL,
  `tm` text,
  `age` bigint DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

--- Schema for table: End_of_Season_Teams_Voting ---
CREATE TABLE `End_of_Season_Teams_Voting` (
  `season` bigint DEFAULT NULL,
  `lg` text,
  `type` text,
  `number_tm` text,
  `position` text,
  `player` text,
  `age` bigint DEFAULT NULL,
  `tm` text,
  `pts_won` double DEFAULT NULL,
  `pts_max` double DEFAULT NULL,
  `share` double DEFAULT NULL,
  `x1st_tm` double DEFAULT NULL,
  `x2nd_tm` double DEFAULT NULL,
  `x3rd_tm` double DEFAULT NULL,
  `seas_id` bigint DEFAULT NULL,
  `player_id` bigint DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

--- Schema for table: Game_Shots ---
CREATE TABLE `Game_Shots` (
  `Season_ID` bigint DEFAULT NULL,
  `Team_ID` bigint DEFAULT NULL,
  `Player_ID` bigint DEFAULT NULL,
  `Position_Group` text,
  `Position` text,
  `Game_Date` text,
  `Game_ID` bigint DEFAULT NULL,
  `Home_Team` text,
  `Away_Team` text,
  `Event_Type` text,
  `Shot_Made` tinyint(1) DEFAULT NULL,
  `Action_Type` text,
  `Shot_Type` text,
  `Basic_Zone` text,
  `Zone_Name` text,
  `Zone_Abb` text,
  `Zone_Range` text,
  `Loc_X` double DEFAULT NULL,
  `Loc_Y` double DEFAULT NULL,
  `Shot_Distance` bigint DEFAULT NULL,
  `Quarter` bigint DEFAULT NULL,
  `Mins_Left` bigint DEFAULT NULL,
  `Secs_Left` bigint DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

--- Schema for table: NBA_Finals_and_MVP ---
CREATE TABLE `NBA_Finals_and_MVP` (
  `index` bigint DEFAULT NULL,
  `Year` bigint DEFAULT NULL,
  `Western Champion` text,
  `Eastern Champion` text,
  `Result` text,
  `NBA Champion` text,
  `NBA Vice-Champion` text,
  `Final Sweep ?` tinyint(1) DEFAULT NULL,
  `MVP Name` text,
  `MVP Height (m)` double DEFAULT NULL,
  `MVP Height (ft)` double DEFAULT NULL,
  `MVP Position` text,
  `MVP Team` text,
  `MVP Nationality` text,
  `MVP status` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

--- Schema for table: Opponent_Stats_Per_100_Poss ---
CREATE TABLE `Opponent_Stats_Per_100_Poss` (
  `season` bigint DEFAULT NULL,
  `lg` text,
  `team` text,
  `abbreviation` text,
  `playoffs` tinyint(1) DEFAULT NULL,
  `g` bigint DEFAULT NULL,
  `mp` bigint DEFAULT NULL,
  `opp_fg_per_100_poss` double DEFAULT NULL,
  `opp_fga_per_100_poss` double DEFAULT NULL,
  `opp_fg_percent` double DEFAULT NULL,
  `opp_x3p_per_100_poss` double DEFAULT NULL,
  `opp_x3pa_per_100_poss` double DEFAULT NULL,
  `opp_x3p_percent` double DEFAULT NULL,
  `opp_x2p_per_100_poss` double DEFAULT NULL,
  `opp_x2pa_per_100_poss` double DEFAULT NULL,
  `opp_x2p_percent` double DEFAULT NULL,
  `opp_ft_per_100_poss` double DEFAULT NULL,
  `opp_fta_per_100_poss` double DEFAULT NULL,
  `opp_ft_percent` double DEFAULT NULL,
  `opp_orb_per_100_poss` double DEFAULT NULL,
  `opp_drb_per_100_poss` double DEFAULT NULL,
  `opp_trb_per_100_poss` double DEFAULT NULL,
  `opp_ast_per_100_poss` double DEFAULT NULL,
  `opp_stl_per_100_poss` double DEFAULT NULL,
  `opp_blk_per_100_poss` double DEFAULT NULL,
  `opp_tov_per_100_poss` double DEFAULT NULL,
  `opp_pf_per_100_poss` double DEFAULT NULL,
  `opp_pts_per_100_poss` double DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

--- Schema for table: Opponent_Stats_Per_Game ---
CREATE TABLE `Opponent_Stats_Per_Game` (
  `season` bigint DEFAULT NULL,
  `lg` text,
  `team` text,
  `abbreviation` text,
  `playoffs` tinyint(1) DEFAULT NULL,
  `g` double DEFAULT NULL,
  `mp_per_game` double DEFAULT NULL,
  `opp_fg_per_game` double DEFAULT NULL,
  `opp_fga_per_game` double DEFAULT NULL,
  `opp_fg_percent` double DEFAULT NULL,
  `opp_x3p_per_game` double DEFAULT NULL,
  `opp_x3pa_per_game` double DEFAULT NULL,
  `opp_x3p_percent` double DEFAULT NULL,
  `opp_x2p_per_game` double DEFAULT NULL,
  `opp_x2pa_per_game` double DEFAULT NULL,
  `opp_x2p_percent` double DEFAULT NULL,
  `opp_ft_per_game` double DEFAULT NULL,
  `opp_fta_per_game` double DEFAULT NULL,
  `opp_ft_percent` double DEFAULT NULL,
  `opp_orb_per_game` double DEFAULT NULL,
  `opp_drb_per_game` double DEFAULT NULL,
  `opp_trb_per_game` double DEFAULT NULL,
  `opp_ast_per_game` double DEFAULT NULL,
  `opp_stl_per_game` double DEFAULT NULL,
  `opp_blk_per_game` double DEFAULT NULL,
  `opp_tov_per_game` double DEFAULT NULL,
  `opp_pf_per_game` double DEFAULT NULL,
  `opp_pts_per_game` double DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

--- Schema for table: Opponent_Totals ---
CREATE TABLE `Opponent_Totals` (
  `season` bigint DEFAULT NULL,
  `lg` text,
  `team` text,
  `abbreviation` text,
  `playoffs` tinyint(1) DEFAULT NULL,
  `g` double DEFAULT NULL,
  `mp` double DEFAULT NULL,
  `opp_fg` double DEFAULT NULL,
  `opp_fga` double DEFAULT NULL,
  `opp_fg_percent` double DEFAULT NULL,
  `opp_x3p` double DEFAULT NULL,
  `opp_x3pa` double DEFAULT NULL,
  `opp_x3p_percent` double DEFAULT NULL,
  `opp_x2p` double DEFAULT NULL,
  `opp_x2pa` double DEFAULT NULL,
  `opp_x2p_percent` double DEFAULT NULL,
  `opp_ft` double DEFAULT NULL,
  `opp_fta` double DEFAULT NULL,
  `opp_ft_percent` double DEFAULT NULL,
  `opp_orb` double DEFAULT NULL,
  `opp_drb` double DEFAULT NULL,
  `opp_trb` double DEFAULT NULL,
  `opp_ast` double DEFAULT NULL,
  `opp_stl` double DEFAULT NULL,
  `opp_blk` double DEFAULT NULL,
  `opp_tov` double DEFAULT NULL,
  `opp_pf` double DEFAULT NULL,
  `opp_pts` double DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

--- Schema for table: Per_100_Poss ---
CREATE TABLE `Per_100_Poss` (
  `seas_id` bigint DEFAULT NULL,
  `season` bigint DEFAULT NULL,
  `player_id` bigint DEFAULT NULL,
  `player` text,
  `birth_year` double DEFAULT NULL,
  `pos` text,
  `age` bigint DEFAULT NULL,
  `experience` bigint DEFAULT NULL,
  `lg` text,
  `tm` text,
  `g` bigint DEFAULT NULL,
  `gs` double DEFAULT NULL,
  `mp` bigint DEFAULT NULL,
  `fg_per_100_poss` double DEFAULT NULL,
  `fga_per_100_poss` double DEFAULT NULL,
  `fg_percent` double DEFAULT NULL,
  `x3p_per_100_poss` double DEFAULT NULL,
  `x3pa_per_100_poss` double DEFAULT NULL,
  `x3p_percent` double DEFAULT NULL,
  `x2p_per_100_poss` double DEFAULT NULL,
  `x2pa_per_100_poss` double DEFAULT NULL,
  `x2p_percent` double DEFAULT NULL,
  `ft_per_100_poss` double DEFAULT NULL,
  `fta_per_100_poss` double DEFAULT NULL,
  `ft_percent` double DEFAULT NULL,
  `orb_per_100_poss` double DEFAULT NULL,
  `drb_per_100_poss` double DEFAULT NULL,
  `trb_per_100_poss` double DEFAULT NULL,
  `ast_per_100_poss` double DEFAULT NULL,
  `stl_per_100_poss` double DEFAULT NULL,
  `blk_per_100_poss` double DEFAULT NULL,
  `tov_per_100_poss` double DEFAULT NULL,
  `pf_per_100_poss` double DEFAULT NULL,
  `pts_per_100_poss` double DEFAULT NULL,
  `o_rtg` double DEFAULT NULL,
  `d_rtg` double DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

--- Schema for table: Per_36_Minutes ---
CREATE TABLE `Per_36_Minutes` (
  `seas_id` bigint DEFAULT NULL,
  `season` bigint DEFAULT NULL,
  `player_id` bigint DEFAULT NULL,
  `player` text,
  `birth_year` double DEFAULT NULL,
  `pos` text,
  `age` double DEFAULT NULL,
  `experience` bigint DEFAULT NULL,
  `lg` text,
  `tm` text,
  `g` bigint DEFAULT NULL,
  `gs` double DEFAULT NULL,
  `mp` double DEFAULT NULL,
  `fg_per_36_min` double DEFAULT NULL,
  `fga_per_36_min` double DEFAULT NULL,
  `fg_percent` double DEFAULT NULL,
  `x3p_per_36_min` double DEFAULT NULL,
  `x3pa_per_36_min` double DEFAULT NULL,
  `x3p_percent` double DEFAULT NULL,
  `x2p_per_36_min` double DEFAULT NULL,
  `x2pa_per_36_min` double DEFAULT NULL,
  `x2p_percent` double DEFAULT NULL,
  `ft_per_36_min` double DEFAULT NULL,
  `fta_per_36_min` double DEFAULT NULL,
  `ft_percent` double DEFAULT NULL,
  `orb_per_36_min` double DEFAULT NULL,
  `drb_per_36_min` double DEFAULT NULL,
  `trb_per_36_min` double DEFAULT NULL,
  `ast_per_36_min` double DEFAULT NULL,
  `stl_per_36_min` double DEFAULT NULL,
  `blk_per_36_min` double DEFAULT NULL,
  `tov_per_36_min` double DEFAULT NULL,
  `pf_per_36_min` double DEFAULT NULL,
  `pts_per_36_min` double DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

--- Schema for table: Player_Award_Shares ---
CREATE TABLE `Player_Award_Shares` (
  `season` bigint DEFAULT NULL,
  `award` text,
  `player` text,
  `age` bigint DEFAULT NULL,
  `tm` text,
  `first` double DEFAULT NULL,
  `pts_won` double DEFAULT NULL,
  `pts_max` double DEFAULT NULL,
  `share` double DEFAULT NULL,
  `winner` tinyint(1) DEFAULT NULL,
  `seas_id` bigint DEFAULT NULL,
  `player_id` bigint DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

--- Schema for table: Player_Career_Info ---
CREATE TABLE `Player_Career_Info` (
  `player_id` bigint DEFAULT NULL,
  `player` text,
  `birth_year` double DEFAULT NULL,
  `hof` tinyint(1) DEFAULT NULL,
  `num_seasons` bigint DEFAULT NULL,
  `first_seas` bigint DEFAULT NULL,
  `last_seas` bigint DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

--- Schema for table: Player_Per_Game ---
CREATE TABLE `Player_Per_Game` (
  `seas_id` bigint DEFAULT NULL,
  `season` bigint DEFAULT NULL,
  `player_id` bigint DEFAULT NULL,
  `player` text,
  `birth_year` double DEFAULT NULL,
  `pos` text,
  `age` double DEFAULT NULL,
  `experience` bigint DEFAULT NULL,
  `lg` text,
  `tm` text,
  `g` bigint DEFAULT NULL,
  `gs` double DEFAULT NULL,
  `mp_per_game` double DEFAULT NULL,
  `fg_per_game` double DEFAULT NULL,
  `fga_per_game` double DEFAULT NULL,
  `fg_percent` double DEFAULT NULL,
  `x3p_per_game` double DEFAULT NULL,
  `x3pa_per_game` double DEFAULT NULL,
  `x3p_percent` double DEFAULT NULL,
  `x2p_per_game` double DEFAULT NULL,
  `x2pa_per_game` double DEFAULT NULL,
  `x2p_percent` double DEFAULT NULL,
  `e_fg_percent` double DEFAULT NULL,
  `ft_per_game` double DEFAULT NULL,
  `fta_per_game` double DEFAULT NULL,
  `ft_percent` double DEFAULT NULL,
  `orb_per_game` double DEFAULT NULL,
  `drb_per_game` double DEFAULT NULL,
  `trb_per_game` double DEFAULT NULL,
  `ast_per_game` double DEFAULT NULL,
  `stl_per_game` double DEFAULT NULL,
  `blk_per_game` double DEFAULT NULL,
  `tov_per_game` double DEFAULT NULL,
  `pf_per_game` double DEFAULT NULL,
  `pts_per_game` double DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

--- Schema for table: Player_Play_By_Play ---
CREATE TABLE `Player_Play_By_Play` (
  `seas_id` double DEFAULT NULL,
  `season` bigint DEFAULT NULL,
  `player_id` double DEFAULT NULL,
  `player` text,
  `birth_year` double DEFAULT NULL,
  `pos` text,
  `age` bigint DEFAULT NULL,
  `experience` double DEFAULT NULL,
  `lg` text,
  `tm` text,
  `g` bigint DEFAULT NULL,
  `mp` bigint DEFAULT NULL,
  `pg_percent` double DEFAULT NULL,
  `sg_percent` double DEFAULT NULL,
  `sf_percent` double DEFAULT NULL,
  `pf_percent` double DEFAULT NULL,
  `c_percent` double DEFAULT NULL,
  `on_court_plus_minus_per_100_poss` double DEFAULT NULL,
  `net_plus_minus_per_100_poss` double DEFAULT NULL,
  `bad_pass_turnover` bigint DEFAULT NULL,
  `lost_ball_turnover` bigint DEFAULT NULL,
  `shooting_foul_committed` bigint DEFAULT NULL,
  `offensive_foul_committed` bigint DEFAULT NULL,
  `shooting_foul_drawn` bigint DEFAULT NULL,
  `offensive_foul_drawn` double DEFAULT NULL,
  `points_generated_by_assists` bigint DEFAULT NULL,
  `and1` bigint DEFAULT NULL,
  `fga_blocked` bigint DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

--- Schema for table: Player_Season_Info ---
CREATE TABLE `Player_Season_Info` (
  `season` bigint DEFAULT NULL,
  `seas_id` bigint DEFAULT NULL,
  `player_id` bigint DEFAULT NULL,
  `player` text,
  `birth_year` double DEFAULT NULL,
  `pos` text,
  `age` double DEFAULT NULL,
  `lg` text,
  `tm` text,
  `experience` bigint DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

--- Schema for table: Player_Shooting ---
CREATE TABLE `Player_Shooting` (
  `seas_id` bigint DEFAULT NULL,
  `season` bigint DEFAULT NULL,
  `player_id` bigint DEFAULT NULL,
  `player` text,
  `birth_year` double DEFAULT NULL,
  `pos` text,
  `age` bigint DEFAULT NULL,
  `experience` bigint DEFAULT NULL,
  `lg` text,
  `tm` text,
  `g` bigint DEFAULT NULL,
  `mp` bigint DEFAULT NULL,
  `fg_percent` double DEFAULT NULL,
  `avg_dist_fga` double DEFAULT NULL,
  `percent_fga_from_x2p_range` double DEFAULT NULL,
  `percent_fga_from_x0_3_range` double DEFAULT NULL,
  `percent_fga_from_x3_10_range` double DEFAULT NULL,
  `percent_fga_from_x10_16_range` double DEFAULT NULL,
  `percent_fga_from_x16_3p_range` double DEFAULT NULL,
  `percent_fga_from_x3p_range` double DEFAULT NULL,
  `fg_percent_from_x2p_range` double DEFAULT NULL,
  `fg_percent_from_x0_3_range` double DEFAULT NULL,
  `fg_percent_from_x3_10_range` double DEFAULT NULL,
  `fg_percent_from_x10_16_range` double DEFAULT NULL,
  `fg_percent_from_x16_3p_range` double DEFAULT NULL,
  `fg_percent_from_x3p_range` double DEFAULT NULL,
  `percent_assisted_x2p_fg` double DEFAULT NULL,
  `percent_assisted_x3p_fg` double DEFAULT NULL,
  `percent_dunks_of_fga` double DEFAULT NULL,
  `num_of_dunks` bigint DEFAULT NULL,
  `percent_corner_3s_of_3pa` double DEFAULT NULL,
  `corner_3_point_percent` double DEFAULT NULL,
  `num_heaves_attempted` bigint DEFAULT NULL,
  `num_heaves_made` bigint DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

--- Schema for table: Player_Totals ---
CREATE TABLE `Player_Totals` (
  `seas_id` bigint DEFAULT NULL,
  `season` bigint DEFAULT NULL,
  `player_id` bigint DEFAULT NULL,
  `player` text,
  `birth_year` double DEFAULT NULL,
  `pos` text,
  `age` double DEFAULT NULL,
  `experience` bigint DEFAULT NULL,
  `lg` text,
  `tm` text,
  `g` bigint DEFAULT NULL,
  `gs` double DEFAULT NULL,
  `mp` double DEFAULT NULL,
  `fg` bigint DEFAULT NULL,
  `fga` bigint DEFAULT NULL,
  `fg_percent` double DEFAULT NULL,
  `x3p` double DEFAULT NULL,
  `x3pa` double DEFAULT NULL,
  `x3p_percent` double DEFAULT NULL,
  `x2p` bigint DEFAULT NULL,
  `x2pa` bigint DEFAULT NULL,
  `x2p_percent` double DEFAULT NULL,
  `e_fg_percent` double DEFAULT NULL,
  `ft` bigint DEFAULT NULL,
  `fta` bigint DEFAULT NULL,
  `ft_percent` double DEFAULT NULL,
  `orb` double DEFAULT NULL,
  `drb` double DEFAULT NULL,
  `trb` double DEFAULT NULL,
  `ast` bigint DEFAULT NULL,
  `stl` double DEFAULT NULL,
  `blk` double DEFAULT NULL,
  `tov` double DEFAULT NULL,
  `pf` bigint DEFAULT NULL,
  `pts` bigint DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

--- Schema for table: Team_Abbrev ---
CREATE TABLE `Team_Abbrev` (
  `season` bigint DEFAULT NULL,
  `lg` text,
  `team` text,
  `playoffs` tinyint(1) DEFAULT NULL,
  `abbreviation` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

--- Schema for table: Team_Stats_Per_100_Poss ---
CREATE TABLE `Team_Stats_Per_100_Poss` (
  `season` bigint DEFAULT NULL,
  `lg` text,
  `team` text,
  `abbreviation` text,
  `playoffs` tinyint(1) DEFAULT NULL,
  `g` bigint DEFAULT NULL,
  `mp` bigint DEFAULT NULL,
  `fg_per_100_poss` double DEFAULT NULL,
  `fga_per_100_poss` double DEFAULT NULL,
  `fg_percent` double DEFAULT NULL,
  `x3p_per_100_poss` double DEFAULT NULL,
  `x3pa_per_100_poss` double DEFAULT NULL,
  `x3p_percent` double DEFAULT NULL,
  `x2p_per_100_poss` double DEFAULT NULL,
  `x2pa_per_100_poss` double DEFAULT NULL,
  `x2p_percent` double DEFAULT NULL,
  `ft_per_100_poss` double DEFAULT NULL,
  `fta_per_100_poss` double DEFAULT NULL,
  `ft_percent` double DEFAULT NULL,
  `orb_per_100_poss` double DEFAULT NULL,
  `drb_per_100_poss` double DEFAULT NULL,
  `trb_per_100_poss` double DEFAULT NULL,
  `ast_per_100_poss` double DEFAULT NULL,
  `stl_per_100_poss` double DEFAULT NULL,
  `blk_per_100_poss` double DEFAULT NULL,
  `tov_per_100_poss` double DEFAULT NULL,
  `pf_per_100_poss` double DEFAULT NULL,
  `pts_per_100_poss` double DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

--- Schema for table: Team_Stats_Per_Game ---
CREATE TABLE `Team_Stats_Per_Game` (
  `season` bigint DEFAULT NULL,
  `lg` text,
  `team` text,
  `abbreviation` text,
  `playoffs` tinyint(1) DEFAULT NULL,
  `g` double DEFAULT NULL,
  `mp_per_game` double DEFAULT NULL,
  `fg_per_game` double DEFAULT NULL,
  `fga_per_game` double DEFAULT NULL,
  `fg_percent` double DEFAULT NULL,
  `x3p_per_game` double DEFAULT NULL,
  `x3pa_per_game` double DEFAULT NULL,
  `x3p_percent` double DEFAULT NULL,
  `x2p_per_game` double DEFAULT NULL,
  `x2pa_per_game` double DEFAULT NULL,
  `x2p_percent` double DEFAULT NULL,
  `ft_per_game` double DEFAULT NULL,
  `fta_per_game` double DEFAULT NULL,
  `ft_percent` double DEFAULT NULL,
  `orb_per_game` double DEFAULT NULL,
  `drb_per_game` double DEFAULT NULL,
  `trb_per_game` double DEFAULT NULL,
  `ast_per_game` double DEFAULT NULL,
  `stl_per_game` double DEFAULT NULL,
  `blk_per_game` double DEFAULT NULL,
  `tov_per_game` double DEFAULT NULL,
  `pf_per_game` double DEFAULT NULL,
  `pts_per_game` double DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

--- Schema for table: Team_Summaries ---
CREATE TABLE `Team_Summaries` (
  `season` bigint DEFAULT NULL,
  `lg` text,
  `team` text,
  `abbreviation` text,
  `playoffs` tinyint(1) DEFAULT NULL,
  `age` double DEFAULT NULL,
  `w` double DEFAULT NULL,
  `l` double DEFAULT NULL,
  `pw` double DEFAULT NULL,
  `pl` double DEFAULT NULL,
  `mov` double DEFAULT NULL,
  `sos` double DEFAULT NULL,
  `srs` double DEFAULT NULL,
  `o_rtg` double DEFAULT NULL,
  `d_rtg` double DEFAULT NULL,
  `n_rtg` double DEFAULT NULL,
  `pace` double DEFAULT NULL,
  `f_tr` double DEFAULT NULL,
  `x3p_ar` double DEFAULT NULL,
  `ts_percent` double DEFAULT NULL,
  `e_fg_percent` double DEFAULT NULL,
  `tov_percent` double DEFAULT NULL,
  `orb_percent` double DEFAULT NULL,
  `ft_fga` double DEFAULT NULL,
  `opp_e_fg_percent` double DEFAULT NULL,
  `opp_tov_percent` double DEFAULT NULL,
  `opp_drb_percent` double DEFAULT NULL,
  `opp_ft_fga` double DEFAULT NULL,
  `arena` text,
  `attend` double DEFAULT NULL,
  `attend_g` double DEFAULT NULL